#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Environment variables
export TERMINAL='gnome-terminal'
export EDITOR='gvim'

# Aliases
alias mkdir='mkdir -p'
alias rm='trash'
alias vim='gvim -v'
alias nmcli='nmcli -p'
